spring:
  datasource:
    url: jdbc:oracle:thin:@xxxx
    username: xxx
    password: xxx
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
